# Generated by Django 5.0.6 on 2024-05-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sub_category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
